### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by UlyssesWu** [mes51/Kuromoji.NET#1]
_You can always trust .NET._

It's nice to see that you've spent your time and effort to port this (yet another) java lib.

However, when you want to build a quick prototype in C# with a java lib imported, sometimes you can try **IKVM**.

You can compile a .NET dll from a jar using `ikvmc -target:library`, and the result will be like this:
![kuro](https://user-images.githubusercontent.com/4312781/47269276-19d10080-d58e-11e8-9c97-517e00e6cc10.png)

Still it won't be as perfect as a .NET port (as you did) due to some java "features" like generic erasing... But it should behave (almost) same as the original java lib.

**Comment by mes51** [comment]
Thank you show me a nice tool!
I try use this tool for testing Kuromoji.NET, and next prototyping.

**Comment by UlyssesWu** [comment]
Thanks & good luck!
